API_KEY: null
HPC:
  hostname: null
  localdir: /home
  remotedir: null
sbatch:
  account: ''
  error: err.txt
  job-name: no_name
  mem-per-cpu: 2400M
  ntasks: 64
  output: out.txt
  time: "01:00:00"
job_script_filename: job.sh