API_KEY: null
HPC:
  hostname: null
  localdir: /home
  remotedir: null
dbconfig:
  vasp:
    collection: vasp
    database: pynter
    host: 127.0.0.1
    password: null
    port: 27017
    user: null
sbatch:
  account: ''
  error: err.%j
  job-name: no_name
  mem-per-cpu: 2400M
  ntasks: 64
  output: out.%j
  time: "01:00:00"
job_script_filename: job.sh